### ISSUE TITLE
wlogout "exit" option broken

### ISSUE THREAD

**Issue by g5ostXa** [g5ostXa/hyprarch2#78]
When running `wlogout`, selecting the "exit" option does nothing.

**Comment by khushal-banks** [comment]
In hypr power-scipt [replace this line](https://github.com/g5ostXa/hyprarch2/blob/0e3d608297e9916f263ff5f2e67d76676357dee2/src/Scripts/hypr/power.sh#L9) with following:

`hyprctl dispatch exit 0`

**Comment by g5ostXa** [comment]
Good job. I wonder if it would be better to use `uwsm stop`, though. 
Will look into it.

**Comment by khushal-banks** [comment]
> I wonder if it would be better to use `uwsm stop`, though.

Are you launching hyprland using UWSM?

**Comment by g5ostXa** [comment]
Yes. That's why it makes sens that `killall hyprland -9` no longer works.

**Comment by khushal-banks** [comment]
I am not using it and it says,
![image](https://github.com/user-attachments/assets/ae355af1-c215-4aed-9f1a-4964ce7d8e5c)

I don't know much about uwsm. So, that's why i am having a difficult time in understanding how you are using it. Maybe this article would be helpful [Launching Hyprland with uwsm](https://wiki.hyprland.org/Useful-Utilities/Systemd-start/#launching-hyprland-with-uwsm) especially, the section `Launching applications inside session`

**Comment by g5ostXa** [comment]
I can confirm that on my system, uwsm stop works.
